name:                application
version:             0.1.0.0
github:              "githubuser/application"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/application#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- mtl
- warp
- time
- hspec
- neat-interpolation
- text
- bytestring
- req
- http-client
- regex-tdfa

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - application
  worker-exe:
    main:                Main.hs
    source-dirs:         worker
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - application

tests:
  application-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - application
